import type { Topic } from "../types";

// SAMPLE / TEMPLATE TOPIC. Demonstrates the full contract: AoPS guide sections
// (discovery + whyItWorks + strategies + diagrams), flashcards + formulae,
// MCQs and QAs tagged with difficulty + hint ladders + multi-method solutions.

const fractions: Topic = {
  id: "fractions",
  title: "Fractions",
  subject: "Maths",
  chapter: "NCERT Ch. 7 (Fractions)",
  icon: "🍕",
  color: "#f97316",
  intro:
    "A fraction is a way of talking about a part of a whole — or a part of a group. Once you can picture fractions as pieces of a bar or slices of a pizza, adding, comparing and simplifying them stops being scary and starts being fun.",
  guide: [
    {
      heading: "What a fraction really means",
      discovery: {
        problem:
          "Two pizzas are the same size. One is cut into 4 equal slices, the other into 8. You take 3 slices from the first and 6 from the second. Did you eat the same amount, or more from one?",
        idea: "A fraction a/b means 'split the whole into b equal parts, then take a of them'. 3/4 and 6/8 cover exactly the same amount — they are equivalent fractions.",
      },
      body:
        "In the fraction **3/4**, the bottom number (**denominator**) tells you how many equal parts the whole is split into. The top number (**numerator**) tells you how many of those parts you take.\n\nThe key word is *equal*. If the parts are not equal, the fraction doesn't mean anything sensible.",
      keyPoints: [
        "Denominator = number of equal parts the whole is cut into.",
        "Numerator = how many parts you take.",
        "The same amount can be written many ways (3/4 = 6/8 = 9/12).",
      ],
      diagrams: [
        '<svg viewBox="0 0 320 80" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A bar split into four equal parts with three shaded"><rect x="10" y="20" width="300" height="40" fill="none" stroke="#334155" stroke-width="2"/><rect x="10" y="20" width="75" height="40" fill="#fb923c"/><rect x="85" y="20" width="75" height="40" fill="#fb923c"/><rect x="160" y="20" width="75" height="40" fill="#fb923c"/><line x1="85" y1="20" x2="85" y2="60" stroke="#334155" stroke-width="2"/><line x1="160" y1="20" x2="160" y2="60" stroke="#334155" stroke-width="2"/><line x1="235" y1="20" x2="235" y2="60" stroke="#334155" stroke-width="2"/><text x="160" y="14" text-anchor="middle" font-size="13" fill="#334155">three quarters shaded = 3/4</text></svg>',
      ],
      whyItWorks:
        "Multiplying top and bottom by the same number just cuts every piece into more equal pieces — the shaded amount never changes. That is why 3/4 = 6/8.",
      strategies: ["Draw a diagram", "Look for equal parts"],
    },
    {
      heading: "Equivalent fractions and simplest form",
      body:
        "To make an **equivalent fraction**, multiply (or divide) the numerator and denominator by the *same* number.\n\nA fraction is in **simplest form** (lowest terms) when the only number that divides both top and bottom is 1. To simplify, divide top and bottom by their HCF (highest common factor).",
      keyPoints: [
        "Multiply/divide top and bottom by the same number → equivalent fraction.",
        "Simplest form: divide by the HCF of numerator and denominator.",
        "12/18 → divide by 6 → 2/3.",
      ],
      whyItWorks:
        "Dividing top and bottom by their HCF removes the largest shared factor in one step, so nothing is left to cancel.",
      strategies: ["Find a pattern", "Use factors (HCF)"],
    },
    {
      heading: "Comparing, adding and subtracting fractions",
      discovery: {
        problem: "Which is bigger, 2/3 or 3/5? You are not allowed to use a calculator.",
        idea: "Rewrite both with the SAME denominator (a common denominator) so you are comparing equal-sized pieces. 2/3 = 10/15 and 3/5 = 9/15, so 2/3 is bigger.",
      },
      body:
        "To **compare, add or subtract** fractions you first make the denominators the same — a **common denominator** (often the LCM of the denominators). Then you simply compare or add/subtract the numerators, keeping the denominator.\n\nExample: 1/4 + 2/3 = 3/12 + 8/12 = **11/12**.",
      keyPoints: [
        "Same denominator → just add/subtract the numerators.",
        "Use the LCM of the denominators as the common denominator.",
        "Always give the final answer in simplest form.",
      ],
      diagrams: [
        '<svg viewBox="0 0 320 110" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two bars showing one quarter plus two thirds rewritten over twelfths"><text x="0" y="22" font-size="12" fill="#334155">1/4 = 3/12</text><rect x="90" y="10" width="216" height="20" fill="none" stroke="#334155"/><rect x="90" y="10" width="54" height="20" fill="#60a5fa"/><text x="0" y="62" font-size="12" fill="#334155">2/3 = 8/12</text><rect x="90" y="50" width="216" height="20" fill="none" stroke="#334155"/><rect x="90" y="50" width="144" height="20" fill="#34d399"/><text x="0" y="100" font-size="12" fill="#334155">sum = 11/12</text><rect x="90" y="88" width="216" height="20" fill="none" stroke="#334155"/><rect x="90" y="88" width="198" height="20" fill="#fbbf24"/></svg>',
      ],
      whyItWorks:
        "You can only add things that are the same size. Quarters and thirds are different-sized pieces, so we re-cut both into twelfths first — then they add like ordinary counting.",
      strategies: ["Use a common denominator", "Draw a diagram"],
      thinkDeeper:
        "Can you add 1/2 + 1/3 + 1/6 in your head? What clever common denominator makes it easy?",
    },
  ],
  learn: {
    flashcards: [
      { front: "What does the denominator tell you?", back: "How many equal parts the whole is split into." },
      { front: "How do you simplify a fraction?", back: "Divide the numerator and denominator by their HCF." },
      { front: "How do you add fractions with different denominators?", back: "Rewrite them over a common denominator (the LCM), then add the numerators." },
      { front: "What is an improper fraction?", back: "A fraction where the numerator is bigger than (or equal to) the denominator, e.g. 7/4." },
      { front: "Convert 7/4 to a mixed number.", back: "1 3/4 (because 7 ÷ 4 = 1 remainder 3)." },
    ],
    formulae: [
      { name: "Equivalent fraction", rule: "a/b = (a×k)/(b×k) for any non-zero k" },
      { name: "Simplest form", rule: "Divide top and bottom by HCF(a, b)" },
      { name: "Add/subtract", rule: "a/c ± b/c = (a ± b)/c (same denominator)" },
    ],
  },
  quiz: {
    mcq: [
      {
        id: "fra-mcq-q01",
        question: "What fraction of this shape is shaded if 3 out of 4 equal parts are coloured?",
        options: ["3/4", "4/3", "1/4", "3/7"],
        answerIndex: 0,
        explanation: "3 shaded parts out of 4 equal parts is 3/4. The numerator counts shaded parts; the denominator counts all equal parts.",
        guideRef: "What a fraction really means",
        difficulty: "warmup",
        strategy: "Draw a diagram",
      },
      {
        id: "fra-mcq-q02",
        question: "Which fraction is equivalent to 2/3?",
        options: ["3/4", "6/9", "4/9", "2/6"],
        answerIndex: 1,
        explanation: "Multiply top and bottom of 2/3 by 3: (2×3)/(3×3) = 6/9.",
        guideRef: "Equivalent fractions and simplest form",
        difficulty: "warmup",
      },
      {
        id: "fra-mcq-q03",
        question: "Write 12/18 in its simplest form.",
        options: ["6/9", "2/3", "3/4", "4/6"],
        answerIndex: 1,
        explanation: "HCF of 12 and 18 is 6. Dividing both by 6 gives 2/3.",
        guideRef: "Equivalent fractions and simplest form",
        difficulty: "core",
        hints: [
          "What is the biggest number that divides both 12 and 18?",
          "Both 12 and 18 are divisible by 6.",
          "12 ÷ 6 = 2 and 18 ÷ 6 = 3.",
        ],
        strategy: "Use factors (HCF)",
      },
      {
        id: "fra-mcq-q04",
        question: "Which is greater: 3/5 or 2/3?",
        options: ["3/5", "2/3", "They are equal", "Cannot tell"],
        answerIndex: 1,
        explanation: "Common denominator 15: 3/5 = 9/15 and 2/3 = 10/15, so 2/3 is greater.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "core",
        hints: [
          "Make the denominators the same.",
          "The LCM of 5 and 3 is 15.",
          "Compare 9/15 with 10/15.",
        ],
        strategy: "Use a common denominator",
      },
      {
        id: "fra-mcq-q05",
        question: "What is 1/4 + 2/3?",
        options: ["3/7", "11/12", "3/12", "1/2"],
        answerIndex: 1,
        explanation: "Common denominator 12: 1/4 = 3/12, 2/3 = 8/12, sum = 11/12.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "core",
        hints: ["Find a common denominator for 4 and 3.", "Use 12.", "3/12 + 8/12 = ?"],
        strategy: "Use a common denominator",
      },
      {
        id: "fra-mcq-q06",
        question:
          "A fraction equals 1/2. Its numerator and denominator add up to 27. What is the fraction?",
        options: ["9/18", "13/14", "12/15", "10/17"],
        answerIndex: 0,
        explanation:
          "Fractions equal to 1/2 look like k/2k, so numerator + denominator = 3k = 27, giving k = 9. The fraction is 9/18.",
        guideRef: "Equivalent fractions and simplest form",
        difficulty: "challenge",
        hints: [
          "Every fraction equal to 1/2 can be written as k/(2k).",
          "Then k + 2k = 27.",
          "Solve 3k = 27.",
        ],
        strategy: "Introduce a variable",
      },
      {
        id: "fra-mcq-q07",
        question: "Which of these is a proper fraction?",
        options: ["7/4", "5/5", "3/8", "9/2"],
        answerIndex: 2,
        explanation: "A proper fraction has a numerator smaller than its denominator. 3/8 fits; 7/4 and 9/2 are improper, and 5/5 = 1.",
        guideRef: "What a fraction really means",
        difficulty: "warmup",
      },
      {
        id: "fra-mcq-q08",
        question: "Write the mixed number 1 3/4 as an improper fraction.",
        options: ["7/4", "4/3", "13/4", "1/4"],
        answerIndex: 0,
        explanation: "1 whole = 4/4, plus 3/4 makes 7/4. (Or 1×4 + 3 = 7, over 4.)",
        guideRef: "What a fraction really means",
        difficulty: "warmup",
      },
      {
        id: "fra-mcq-q09",
        question: "What is 3/7 + 2/7?",
        options: ["5/14", "6/7", "5/7", "1/7"],
        answerIndex: 2,
        explanation: "Same denominator, so add the numerators only: (3+2)/7 = 5/7.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "warmup",
      },
      {
        id: "fra-mcq-q10",
        question: "On a number line from 0 to 1 divided into 4 equal parts, which fraction is at the second mark from 0?",
        options: ["1/4", "2/4", "3/4", "1/2 of 4"],
        answerIndex: 1,
        explanation: "Each gap is 1/4. The second mark is at 2/4 (which also equals 1/2).",
        guideRef: "What a fraction really means",
        difficulty: "warmup",
      },
      {
        id: "fra-mcq-q11",
        question: "Write 7/4 as a mixed number.",
        options: ["1 3/4", "3 1/4", "1 1/4", "2 3/4"],
        answerIndex: 0,
        explanation: "7 ÷ 4 = 1 remainder 3, so 7/4 = 1 3/4.",
        guideRef: "What a fraction really means",
        difficulty: "core",
        hints: ["How many whole 4s fit into 7?", "One 4, with 3 left over.", "The remainder is the new numerator."],
      },
      {
        id: "fra-mcq-q12",
        question: "Which is greater, 5/8 or 3/4?",
        options: ["5/8", "3/4", "They are equal", "Cannot tell"],
        answerIndex: 1,
        explanation: "3/4 = 6/8, and 6/8 > 5/8, so 3/4 is greater.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "core",
        hints: ["Write 3/4 with denominator 8.", "3/4 = 6/8.", "Compare 6/8 with 5/8."],
        strategy: "Use a common denominator",
      },
      {
        id: "fra-mcq-q13",
        question: "What is 2/3 of 18?",
        options: ["6", "9", "12", "15"],
        answerIndex: 2,
        explanation: "Find 1/3 of 18 = 6, then 2/3 = 2 × 6 = 12.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "core",
        hints: ["First find 1/3 of 18.", "18 ÷ 3 = 6.", "Multiply by 2."],
        strategy: "Work in steps",
      },
      {
        id: "fra-mcq-q14",
        question: "Put 1/2, 2/3 and 3/4 in order from smallest to largest.",
        options: ["1/2, 2/3, 3/4", "3/4, 2/3, 1/2", "2/3, 1/2, 3/4", "1/2, 3/4, 2/3"],
        answerIndex: 0,
        explanation: "Common denominator 12: 1/2 = 6/12, 2/3 = 8/12, 3/4 = 9/12, so 1/2 < 2/3 < 3/4.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "core",
        hints: ["Rewrite all three over 12.", "6/12, 8/12, 9/12.", "Smallest numerator first."],
        strategy: "Use a common denominator",
      },
      {
        id: "fra-mcq-q15",
        question: "What is 3/5 − 1/3?",
        options: ["2/2", "4/15", "2/15", "1/2"],
        answerIndex: 1,
        explanation: "Common denominator 15: 3/5 = 9/15, 1/3 = 5/15, 9/15 − 5/15 = 4/15.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "core",
        hints: ["LCM of 5 and 3 is 15.", "9/15 − 5/15.", "Subtract numerators only."],
        strategy: "Use a common denominator",
      },
      {
        id: "fra-mcq-q16",
        question: "Write 16/24 in its simplest form.",
        options: ["4/6", "8/12", "2/3", "3/4"],
        answerIndex: 2,
        explanation: "HCF of 16 and 24 is 8. 16 ÷ 8 = 2, 24 ÷ 8 = 3, giving 2/3.",
        guideRef: "Equivalent fractions and simplest form",
        difficulty: "core",
        hints: ["Find the HCF of 16 and 24.", "It is 8.", "Divide both by 8."],
        strategy: "Use factors (HCF)",
      },
      {
        id: "fra-mcq-q17",
        question: "Which is greater, 7/9 or 8/11?",
        options: ["7/9", "8/11", "They are equal", "Cannot compare"],
        answerIndex: 0,
        explanation: "Common denominator 99: 7/9 = 77/99 and 8/11 = 72/99, so 7/9 is greater.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "challenge",
        hints: ["A common denominator is 9 × 11 = 99.", "7/9 = 77/99; 8/11 = 72/99.", "Compare the numerators."],
        strategy: "Use a common denominator",
      },
      {
        id: "fra-mcq-q18",
        question: "What is 1/2 + 1/3 + 1/6?",
        options: ["1", "3/11", "5/6", "2/3"],
        answerIndex: 0,
        explanation: "Over 6: 3/6 + 2/6 + 1/6 = 6/6 = 1.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "challenge",
        hints: ["A common denominator for 2, 3 and 6 is 6.", "3/6 + 2/6 + 1/6.", "Add the numerators: 3+2+1 = 6."],
        strategy: "Use a common denominator",
      },
      {
        id: "fra-mcq-q19",
        question: "Which fraction lies exactly halfway between 1/3 and 1/2?",
        options: ["2/5", "5/12", "1/4", "3/8"],
        answerIndex: 1,
        explanation: "1/3 = 4/12 and 1/2 = 6/12; halfway is 5/12.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "challenge",
        hints: ["Write both over 12.", "4/12 and 6/12.", "What is exactly between them?"],
        strategy: "Use a common denominator",
      },
      {
        id: "fra-mcq-q20",
        question: "In a class, 2/5 play cricket and 1/3 play football. The rest only read. What fraction only read?",
        options: ["3/8", "4/15", "11/15", "1/2"],
        answerIndex: 1,
        explanation: "Players = 2/5 + 1/3 = 6/15 + 5/15 = 11/15. Readers = 1 − 11/15 = 4/15.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "challenge",
        hints: ["Add the cricket and football fractions first.", "2/5 + 1/3 = 11/15.", "Subtract from a whole (15/15)."],
        strategy: "Use a common denominator",
      },
    ],
    qa: [
      {
        id: "fra-qa-q01",
        question: "Explain, using a diagram in words, why 1/2 is the same as 4/8.",
        modelAnswer:
          "If you split a bar into 2 equal parts and shade 1, you shade half the bar. If instead you split the same bar into 8 equal parts, that same half now contains 4 of the small parts. So 1/2 and 4/8 shade exactly the same amount — they are equivalent.",
        markScheme: [
          "split a whole into equal parts | bar into parts",
          "1 of 2 parts is the same shaded area as 4 of 8",
          "multiply top and bottom by 4 | equivalent",
        ],
        commonError: "Thinking 4/8 is bigger because the numbers are bigger.",
        guideRef: "Equivalent fractions and simplest form",
        difficulty: "core",
        hints: ["Picture the same bar cut two different ways.", "How many eighths fit in one half?"],
        solutions: [
          {
            label: "Picture / area model",
            steps: [
              "Draw a bar split into 2; shade 1 half.",
              "Cut each half into 4 → 8 equal parts.",
              "The shaded half now shows 4 of the 8 parts → 4/8.",
            ],
          },
          {
            label: "By calculation",
            steps: ["1/2 = (1×4)/(2×4) = 4/8."],
          },
        ],
      },
      {
        id: "fra-qa-q02",
        question: "Work out 5/6 − 1/4, giving your answer in simplest form. Show your steps.",
        modelAnswer:
          "Common denominator of 6 and 4 is 12. 5/6 = 10/12 and 1/4 = 3/12. 10/12 − 3/12 = 7/12, which is already in simplest form.",
        markScheme: [
          "common denominator 12 | lcm 12",
          "10/12 and 3/12",
          "7/12",
        ],
        commonError: "Subtracting numerators and denominators separately (5−1)/(6−4).",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "core",
        numericAnswer: 7 / 12,
        tolerance: 0.001,
        hints: ["LCM of 6 and 4?", "Rewrite both over 12.", "Subtract the numerators only."],
        solutions: [
          {
            label: "Common denominator",
            steps: ["LCM(6,4) = 12.", "5/6 = 10/12, 1/4 = 3/12.", "10/12 − 3/12 = 7/12 (simplest)."],
          },
        ],
      },
      {
        id: "fra-qa-q03",
        question:
          "Challenge: Riya ate 1/3 of a cake. Her brother ate 1/4 of the same cake. What fraction of the cake is left? What is the smallest number of equal slices the cake could have been cut into so that each portion was a whole number of slices?",
        modelAnswer:
          "Eaten = 1/3 + 1/4 = 4/12 + 3/12 = 7/12. Left = 1 − 7/12 = 5/12. For both 1/3 and 1/4 to be whole numbers of slices, the number of slices must be a common multiple of 3 and 4 — the smallest is the LCM, 12 slices.",
        markScheme: [
          "1/3 + 1/4 = 7/12",
          "left = 5/12",
          "lcm of 3 and 4 | 12 slices",
        ],
        commonError: "Forgetting to subtract from 1 (a whole), or adding 1/3 + 1/4 as 2/7.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "challenge",
        strategy: "Use a common denominator",
        hints: [
          "First find the fraction eaten altogether.",
          "Whole cake = 12/12. Subtract what was eaten.",
          "Slices must divide evenly into thirds AND quarters → common multiple of 3 and 4.",
        ],
        solutions: [
          {
            label: "Step by step",
            steps: [
              "1/3 + 1/4 = 7/12 eaten.",
              "Left = 12/12 − 7/12 = 5/12.",
              "Need a number divisible by 3 and 4 → LCM(3,4) = 12 slices.",
            ],
          },
        ],
      },
      {
        id: "fra-qa-q04",
        question: "Convert the mixed number 2 3/5 into an improper fraction. Show your working.",
        modelAnswer: "2 wholes = 10/5. Add 3/5 to get 13/5. (Or 2×5 + 3 = 13, over 5.)",
        markScheme: ["2 = 10/5 | 2×5 = 10", "add 3", "13/5"],
        commonError: "Writing 2 3/5 as 23/5 by sticking the digits together.",
        guideRef: "What a fraction really means",
        difficulty: "core",
        numericAnswer: 13 / 5,
        tolerance: 0.001,
        hints: ["How many fifths in 2 wholes?", "2 = 10/5.", "Add the extra 3/5."],
      },
      {
        id: "fra-qa-q05",
        question: "Work out 3/8 + 1/4, giving the answer in simplest form.",
        modelAnswer: "1/4 = 2/8, so 3/8 + 2/8 = 5/8, already in simplest form.",
        markScheme: ["1/4 = 2/8 | common denominator 8", "3/8 + 2/8", "5/8"],
        commonError: "Adding to get 4/12 by adding tops and bottoms.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "core",
        numericAnswer: 5 / 8,
        tolerance: 0.001,
        hints: ["Rewrite 1/4 with denominator 8.", "1/4 = 2/8.", "Add the numerators."],
      },
      {
        id: "fra-qa-q06",
        question: "Find 3/4 of ₹240.",
        modelAnswer: "1/4 of 240 = 60, so 3/4 = 3 × 60 = ₹180.",
        markScheme: ["1/4 of 240 = 60 | 240 ÷ 4", "× 3", "₹180 | 180"],
        commonError: "Dividing by 3 instead of multiplying by 3.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "core",
        numericAnswer: 180,
        hints: ["First find 1/4 of ₹240.", "240 ÷ 4 = 60.", "Multiply by 3."],
        solutions: [
          { label: "Find the unit fraction first", steps: ["1/4 of 240 = 60.", "3/4 = 3 × 60 = ₹180."] },
          { label: "Multiply then divide", steps: ["3/4 × 240 = (3 × 240)/4 = 720/4 = ₹180."] },
        ],
      },
      {
        id: "fra-qa-q07",
        question: "Put 2/3, 3/5 and 5/6 in order from smallest to largest. Show how you decided.",
        modelAnswer: "Common denominator 30: 2/3 = 20/30, 3/5 = 18/30, 5/6 = 25/30. So 3/5 < 2/3 < 5/6.",
        markScheme: ["common denominator 30 | lcm 30", "20/30, 18/30, 25/30", "3/5 < 2/3 < 5/6"],
        commonError: "Ordering by numerator or denominator alone.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "core",
        strategy: "Use a common denominator",
        hints: ["LCM of 3, 5 and 6 is 30.", "Rewrite each over 30.", "Order by the numerators."],
      },
      {
        id: "fra-qa-q08",
        question: "A rope is 5/6 m long. A piece of 1/4 m is cut off. How much rope is left? Give the answer in simplest form.",
        modelAnswer: "5/6 − 1/4. Common denominator 12: 10/12 − 3/12 = 7/12 m.",
        markScheme: ["common denominator 12", "10/12 − 3/12", "7/12"],
        commonError: "Subtracting tops and bottoms: (5−1)/(6−4).",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "challenge",
        numericAnswer: 7 / 12,
        tolerance: 0.001,
        strategy: "Use a common denominator",
        hints: ["You need 5/6 − 1/4.", "LCM of 6 and 4 is 12.", "10/12 − 3/12."],
      },
      {
        id: "fra-qa-q09",
        question: "Three friends share a pizza. Aman eats 1/2 and Bharti eats 1/4. What fraction is left for Chetan?",
        modelAnswer: "Eaten = 1/2 + 1/4 = 2/4 + 1/4 = 3/4. Left for Chetan = 1 − 3/4 = 1/4.",
        markScheme: ["1/2 + 1/4 = 3/4", "1 − 3/4", "1/4"],
        commonError: "Forgetting the pizza is one whole (4/4).",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "challenge",
        numericAnswer: 1 / 4,
        tolerance: 0.001,
        strategy: "Work backwards",
        hints: ["First add what Aman and Bharti ate.", "1/2 + 1/4 = 3/4.", "Subtract from the whole, 4/4."],
      },
      {
        id: "fra-qa-q10",
        question: "Challenge: Find a fraction that lies between 1/2 and 5/8. Explain why it works.",
        modelAnswer: "Write 1/2 = 8/16 and 5/8 = 10/16. A fraction between them is 9/16, since 8/16 < 9/16 < 10/16.",
        markScheme: ["1/2 = 8/16 | common denominator 16", "5/8 = 10/16", "9/16 | any fraction strictly between"],
        commonError: "Thinking there is no fraction between two close fractions.",
        guideRef: "Comparing, adding and subtracting fractions",
        difficulty: "challenge",
        strategy: "Use a common denominator",
        hints: [
          "Give both fractions a bigger common denominator so there is 'room' between them.",
          "1/2 = 8/16 and 5/8 = 10/16.",
          "Pick a numerator between 8 and 10.",
        ],
        solutions: [
          {
            label: "Make room with a bigger denominator",
            steps: ["1/2 = 8/16, 5/8 = 10/16.", "9/16 sits between them.", "Check: 0.5 < 0.5625 < 0.625."],
          },
        ],
      },
    ],
  },
  questionBank: {
    mcqPapers: [],
    qaPapers: [],
  },
};

// Group the canonical quiz questions into sittable papers (same objects, no new ids).
fractions.questionBank.mcqPapers = [
  { id: "fra-mcq-paper-1", title: "Fractions — MCQ Set A", questions: fractions.quiz.mcq.slice(0, 10) },
  { id: "fra-mcq-paper-2", title: "Fractions — MCQ Set B", questions: fractions.quiz.mcq.slice(10) },
];
fractions.questionBank.qaPapers = [
  { id: "fra-qa-paper-1", title: "Fractions — Written Practice (Set A)", questions: fractions.quiz.qa.slice(0, 5) },
  { id: "fra-qa-paper-2", title: "Fractions — Written Practice (Set B)", questions: fractions.quiz.qa.slice(5) },
];

export default fractions;
